### PR TITLE
Add direction as third parameter to onOpen

### PR DESCRIPTION
**Pull request by slycoder**

### CODE REVIEW

**Comment by slycoder** [comment]
Hi, @magrinj , what do you think about this change?

**Comment by magrinj** [comment]
Hi @slycoder, yes that's can be good, but I prefer you put your two values `right` and `left` at the top of the file, declared as a `const` in uppercase.

**Comment by slycoder** [comment]
@magrinj , great suggestion.  Done!

**Comment by magrinj** [comment]
Perfect, I merge it! Thanks for your contribution! :)

**Pull request merged**
